/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#899299",
        "secondary-fixed-dim": "#d4bbff",
        "inverse-primary": "#00658c",
        "surface-dim": "#12131d",
        "surface-container-low": "#1a1b26",
        "on-error-container": "#ffdad6",
        "surface-variant": "#333440",
        error: "#ffb4ab",
        "on-primary-fixed-variant": "#004c6a",
        "surface-container-highest": "#333440",
        "on-surface-variant": "#bfc8cf",
        "outline-glass": "#383e5a",
        "on-tertiary": "#660224",
        "text-primary": "#f8f9fc",
        "on-tertiary-fixed": "#400013",
        "surface-container": "#1e1f2a",
        primary: "#c3e6ff",
        "error-container": "#93000a",
        "on-surface": "#e2e1f1",
        "on-secondary-fixed": "#260058",
        "on-secondary": "#3d1b72",
        "primary-fixed": "#c5e7ff",
        "on-tertiary-container": "#942a44",
        "surface-tint": "#7fd0ff",
        "surface-bright": "#383844",
        "inverse-on-surface": "#2f303b",
        surface: "#12131d",
        "on-error": "#690005",
        "tertiary-container": "#ffb1bc",
        "secondary-fixed": "#ebdcff",
        "surface-container-high": "#282935",
        "text-secondary": "#a9b1d6",
        "tertiary-fixed-dim": "#ffb2bc",
        "primary-container": "#7dcfff",
        "warning-neon": "#ff9e64",
        "on-primary-container": "#00587a",
        tertiary: "#ffd9dc",
        "surface-slate": "#24283b",
        "outline-variant": "#3f484e",
        "on-background": "#e2e1f1",
        "surface-container-lowest": "#0c0d18",
        "inverse-surface": "#e2e1f1",
        "secondary-container": "#56378d",
        "on-secondary-fixed-variant": "#54358a",
        "on-primary": "#00344a",
        "surface-dark": "#1f2335",
        background: "#12131d",
        secondary: "#d4bbff",
        "on-tertiary-fixed-variant": "#851e39",
        "success-neon": "#9ece6a",
        "on-secondary-container": "#c8a9ff",
        "primary-fixed-dim": "#7fd0ff",
        "on-primary-fixed": "#001e2d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        lg: "24px",
        xl: "32px",
        md: "16px",
        xs: "4px",
        sm: "8px",
        "margin-mobile": "16px",
        unit: "4px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-base": ["Inter", "sans-serif"],
        "body-bold": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-bold": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "code-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
      keyframes: {
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
      },
      animation: {
        blob: "blob 7s infinite",
      },
    },
  },
  plugins: [],
};
